### ISSUE TITLE
[Feature Request] Native CarPlay support/app

### ISSUE THREAD

**Issue by tehguitarist** [rasmuslos/ShelfPlayer#15] opened 2024-01-17 23:20 UTC
Playback on CarPlay of course works totally fine if a book is “queued” on the phone, or started from the phone (skipping, play/pause, art and name, etc. all pull through), but it’d be great to have a CarPlay interface to start a book from the car touchscreen.

Great app! Love having a native option for ABS written in Swift.

**Comment by woolmonkey** [comment] 2024-02-16 11:37
Do you have the app in test flight? I have heard you need so many users in test flight before they well look at it.  Again just stuff I have heard.

**Comment by rasmuslos** [comment] 2024-02-16 12:44
> Do you have the app in test flight? I have heard you need so many users in test flight before they well look at it. Again just stuff I have heard.

I have actually received the entitlements for AmpFin, without any users in a TestFlight. There are also some issues with app review, so this may take some time

**Comment by sevenlayercookie** [comment] 2024-02-17 00:36
> > Do you have the app in test flight? I have heard you need so many users in test flight before they well look at it. Again just stuff I have heard.
> 
> 
> 
> I have actually received the entitlements for AmpFin, without any users in a TestFlight. There are also some issues with app review, so this may take some time

Oddly enough I applied for CarPlay entitlements for my fork of Audiobookshelf yesterday and was approved within 24 hrs. I gave them very generic information ("an audiobook player app with basic playback controls"). I didn't give the name of the app, and I don't have the fork even registered yet in my developer account.

**Comment by woolmonkey** [comment] 2024-02-17 01:09
Are you releasing the fork?

**Comment by sevenlayercookie** [comment] 2024-02-17 01:54
> Are you releasing the fork?

I haven't even started on the CarPlay part, but yes eventually will publish it and hopefully get it merged into the main Audiobookshelf branch.

**Comment by rasmuslos** [comment] 2024-02-17 08:07
If you are talking about the official app, there is already someone doing an implementation, I would suggest talking to them in #dev-chat (ABS-Discord)

**Comment by rasmuslos** [comment] 2024-02-23 08:41
I have received the entitlements and started to work on the CarPlay app, but this might take some time to finish because you cannot program CarPlay apps in SwiftUI, the language I primarily use.

Also I don't think it is possible to side-load a CarPlay app, or at least quite hard, because you have to have a Apple-Developer account and request the entitlements yourself.

**Comment by sevenlayercookie** [comment] 2024-02-24 08:49
Nice! I have CarPlay entitlements for a different audiobook app and Apple Developer account -- I wonder if I can apply my entitlements to be able to use your CarPlay implementation? Not really sure how all of that works -- I'm brand new to iOS app development.

**Comment by rasmuslos** [comment] 2024-02-24 11:54
> Nice! I have CarPlay entitlements for a different audiobook app and Apple Developer account -- I wonder if I can apply my entitlements to be able to use your CarPlay implementation? Not really sure how all of that works -- I'm brand new to iOS app development.

The entitlement is tied to a bundle identifier, so you would have to reuse the same one, but it should work

**Comment by sevenlayercookie** [comment] 2024-02-27 19:55
> > Nice! I have CarPlay entitlements for a different audiobook app and Apple Developer account -- I wonder if I can apply my entitlements to be able to use your CarPlay implementation? Not really sure how all of that works -- I'm brand new to iOS app development.
> 
> 
> 
> The entitlement is tied to a bundle identifier, so you would have to reuse the same one, but it should work

I got it working; great start so far. I am using this as my daily driver for in car Audiobooks, as yours is the only app that supports both CarPlay and Audiobookshelf. Siri worked extremely well too. Is it only for offline books so far?

**Comment by rasmuslos** [comment] 2024-02-28 06:13
Yes, I will implement an online mode in the future, but I am not yet sure how I should approach some things.

**Comment by rasmuslos** [comment] 2024-02-28 06:23
> > > Nice! I have CarPlay entitlements for a different audiobook app and Apple Developer account -- I wonder if I can apply my entitlements to be able to use your CarPlay implementation? Not really sure how all of that works -- I'm brand new to iOS app development.
> > 
> > 
> > 
> > The entitlement is tied to a bundle identifier, so you would have to reuse the same one, but it should work
> 
> I got it working; great start so far. I am using this as my daily driver for in car Audiobooks, as yours is the only app that supports both CarPlay and Audiobookshelf. Siri worked extremely well too. Is it only for offline books so far?

Just out of curiosity, does Siri work with podcasts / episodes, too?

**Comment by sevenlayercookie** [comment] 2024-02-28 18:21
I don't have any podcasts on my server, but I'm happy to load one and report back.

**Comment by sevenlayercookie** [comment] 2024-02-29 03:17
> > I don't have any podcasts on my server, but I'm happy to load one and report back.
> 
> 
> 
> Thanks!

Was not able to get a podcast to play using Siri, either by referencing the name of the podcast or the specific episode name. It does appear in the list and is playable by tapping the episode in the list.

**Comment by tehguitarist** [comment] 2024-02-29 20:54
This may be redundant because it looks like the app is finally getting reviewed (hopefully it's not another three months between reviews anyway), but was there an easy way to disable CarPlay in the current build? Disabling Siri was easy, but I didn't find an obvious way to disable CarPlay (so I couldn't make a personal build as I'm not sideloading).

Worst case is I'll build a pre-CarPlay version for use until it hits the App Store.

**Comment by rasmuslos** [comment] 2024-02-29 21:17
> This may be redundant because it looks like the app is finally getting reviewed (hopefully it's not another three months between reviews anyway), but was there an easy way to disable CarPlay in the current build? Disabling Siri was easy, but I didn't find an obvious way to disable CarPlay (so I couldn't make a personal build as I'm not sideloading).
> 
> Worst case is I'll build a pre-CarPlay version for use until it hits the App Store.

The app is actually now, but I sadly have to clear some things with my tax councilor first. I really hope I can release the app soon, but I don't want to get into any legal trouble.
I am still committed to continue providing free ipas for anyone that wants to side load the app.

What do you mean by you could not create a personal build? Does Xcode refuse to let you build the project? Can you provide the error message? If Xcode actually throws an error I would have to do some digging to find out how this might be resolved, because disabling Siri is actually done on a code level, while CarPlay is enabled through entitlements received by Apple and managed by Xcode.

Also you don't have to manually disable Siri support, it is sufficient to comment out the `ENABLE_ALL_FEATURES` compiler options in the Base Xcode config file (https://github.com/rasmuslos/ShelfPlayer?tab=readme-ov-file#sideload).

**Comment by tehguitarist** [comment] 2024-03-01 00:59
Not a huge deal, When I go to build, even with the ENABLE_ALL_FEATURES flag removed from the compilation settings it doesn't want to provision. If the app is likely to come out soonish anyway, not a stress in the world. If I delete the Siri section under Signing & Capabilities, I stop getting Siri errors, and just the CarPlay ones.
<img width="599" alt="Screenshot 2024-03-01 at 11 57 24 am" src="https://github.com/rasmuslos/ShelfPlayer/assets/28495826/b5adb1c9-b9b9-4026-aa55-0c252c4bde17">

<img width="495" alt="Screenshot 2024-03-01 at 11 56 21 am" src="https://github.com/rasmuslos/ShelfPlayer/assets/28495826/8e5a7d71-3513-4b48-a3e5-26c638e528e9">

<img width="411" alt="Screenshot 2024-03-01 at 11 56 41 am" src="https://github.com/rasmuslos/ShelfPlayer/assets/28495826/e38dc55c-ef41-479e-84ba-9277977119f1">

Not worth digging too much into, just worth mentioning unless I'm missing something in the build settings.

**Comment by rasmuslos** [comment] 2024-03-01 07:13
Interesting, I thought this might work... There is nothing wrong on your end. I think I can also change the entitlements using the Xcode-config, but the app should get released soon™️.

**Comment by tehguitarist** [comment] 2024-03-25 10:15
CarPlay seems to be working great. One thing I did notice that steering wheel controls on my car (ford focus) doesn’t seem to do anything. On Spotify it skips the song, and on other apps I’ve had it skip 30 seconds. Not sure if this is just a listener, but thought it was worth mentioning.

**Comment by rasmuslos** [comment] 2024-03-25 10:24
> CarPlay seems to be working great. One thing I did notice that steering wheel controls on my car (ford focus) doesn’t seem to do anything. On Spotify it skips the song, and on other apps I’ve had it skip 30 seconds. Not sure if this is just a listener, but thought it was worth mentioning.

This does happen with wireless headphones, too. The problem is that the app only registeres skip not seek commands. If I remember correctly registering seek commands leads to some undesired behavior, but I can look into it.

**Comment by tehguitarist** [comment] 2024-03-25 10:26
It’s not a big deal, the touch screen buttons work and skipping intervals whilst driving isn’t all that common (for me at least).
Just thought it was worth mentioning.

**Comment by rasmuslos** [comment] 2024-03-25 10:43
> It’s not a big deal, the touch screen buttons work and skipping intervals whilst driving isn’t all that common (for me at least). Just thought it was worth mentioning.

It was actually quite easy to fix (at least I hope it works in cars, too). If you register handler for the seek commands but don't enable them they still fire when you use your headphones (or your car) but do not show up anywhere.

Now you can use your headphones to seek, too!

**Comment by tehguitarist** [comment] 2024-04-22 23:21
Not a huge deal, but on the most recent AppStore build ff/rw physical buttons in the car doesn’t skip forward or back in CarPlay. Touchscreen buttons work of course.
Not a big deal, just letting you know.

**Comment by rasmuslos** [comment] 2024-04-23 08:06
> Not a huge deal, but on the most recent AppStore build ff/rw physical buttons in the car doesn’t skip forward or back in CarPlay. Touchscreen buttons work of course. Not a big deal, just letting you know.

Did it work before?

**Comment by rasmuslos** [comment] 2024-04-23 10:12
Do the buttons work in other apps? If they do this is quite curious, because I am not aware of any other events that could be emitted...

**Comment by rasmuslos** [comment] 2024-04-23 10:15
This was completely wrong: There are actually three events: [seekBackwardCommand](https://developer.apple.com/documentation/mediaplayer/mpremotecommandcenter/1618982-seekbackwardcommand) [skipBackwardCommand](https://developer.apple.com/documentation/mediaplayer/mpremotecommandcenter/1618996-skipbackwardcommand) and [previousTrackCommand](https://developer.apple.com/documentation/mediaplayer/mpremotecommandcenter/1618978-previoustrackcommand). Registering all of them should fix this.

**Comment by tehguitarist** [comment] 2024-04-23 10:16
It works to skip songs on Spotify, I’ll have to check the Apple Books app though.
I’ll see how the ABS app does too (which I realise is more “now playing” than it is the actual app.

Just saw your second reply - just leaving the above for reference

**Comment by tehguitarist** [comment] 2024-05-05 22:44
Just gave it 2.4.1 a test, long presses do work on the car steering wheel controls, but short presses don't. As before, not a big deal, just reporting.

**Comment by rasmuslos** [comment] 2024-05-06 06:27
I am kind of running out of ideas...

**Comment by MooreOfNick** [comment] 2024-05-29 16:18
I'm having an issue that ShelfPlayer is not showing any books within the CarPlay app. 

If I ask Siri to play a book, it says "ShelfPlayer is not responding" or something of the like. 

Is this expected behavior? Not sure if this feature is complete yet.

**Comment by saxx0n** [comment] 2024-07-17 01:20
It would be fantastic if there was a selectable option for what the CarPlay screen should default to.  

By that I mean I get in my car and pull up the app, pick and book and start playing.  Works great, drive to wherever im going and get out.  When I get back into my car, the audiobook starts playing again, but it defaults to the book selection screen, and now if I need to access the controls to jump back to remember what is happening I need to click another button to get to the now playing.  It would make more sense (at least to me) that if something is already playing it should go to the now-playing screen, or at least if there was an option somewhere to force it to.

**Comment by saxx0n** [comment] 2024-09-04 15:39
One other issue with CarPlay I have noticed is that it does not pause the audiobook if a notification comes thru. For example, when using Apple Maps, when a turn is announced the book continues playing silently. So when the direction is done the book has advanced. This also happens when receiving/sending voice sms messages.

**Comment by gh0sti** [comment] 2024-09-04 18:18
> One other issue with CarPlay I have noticed is that it does not pause the audiobook if a notification comes thru. For example, when using Apple Maps, when a turn is announced the book continues playing silently. So when the direction is done the book has advanced. This also happens when receiving/sending voice sms messages. 

Weird that issue was supposedly fixed couple versions ago.

**Comment by saxx0n** [comment] 2024-09-04 18:36
> > One other issue with CarPlay I have noticed is that it does not pause the audiobook if a notification comes thru. For example, when using Apple Maps, when a turn is announced the book continues playing silently. So when the direction is done the book has advanced. This also happens when receiving/sending voice sms messages.
> 
> Weird that issue was supposedly fixed couple versions ago.

I can confirm it was happening for me this morning on my fully updated app, on my fully updated phone/car head unit so I donno...

**Comment by rasmuslos** [comment] 2024-09-05 08:24
I updated the routing policy, playback should pause now

**Comment by rasmuslos** [comment] 2024-11-22 17:51
2.5.0 has a propper CarPlay implementation, so I will close this issue

**Closed by rasmuslos** 2024-11-22 17:51 UTC
