### ISSUE TITLE
Sync State Issues

### ISSUE THREAD

**Issue by Vlahn** [rasmuslos/ShelfPlayer#132] opened 2024-09-01 12:51 UTC
I’m trying Shelfplayer on both iOS and iPadOS. I’ve noticed it can be inconsistent in the way it updates the sync position in the audiobookshelf host - particularly if the file is downloaded rather than streamed from the server.

If I continue playback of a downloaded audiobook from the player inside shelfplayer, it won’t update the audiobookshelf server with listening history until I go to the main interface, and directly press the ‘Listen’ button… Then it seems to send a packet to audiobookshelf with the current play position and considers anything played since the last update to be one session. 

This doesn’t feel like intended behaviour. I assumed with the websocket and API in audiobookshelf that a player supporting this would be pinging the server at regular intervals with current listening position. At the very least, I would expect it to do so whenever I pause playback (which is how servers like Plex do this). 

 It’s a real shame as Shelfplayer is a really lovely app to use, as is the functionality in audiobookshelf. I really hope this is something that can be rectified in future updates.

**Comment by rasmuslos** [comment] 2024-09-04 07:46
Duplicate of #119

The enchantments are already implemented and await release!

**Closed** 2024-09-04 07:46 UTC
