### ISSUE TITLE
[Issue] Crash Startup

### ISSUE THREAD

**Issue by Alarez777** [rasmuslos/ShelfPlayer#34] opened 2024-01-30 22:22 UTC
Use sideloadly for installation. I log in and it works fine until I change the library to a podcast library. When I do that it closes and then when I try to open it it doesn't work anymore and it just closes.
Attached is a video of what happens.
https://github.com/rasmuslos/ShelfPlayer/assets/60858814/bed86ee1-3317-4c80-ba33-a6211cb2664a

**Comment by gh0sti** [comment] 2024-01-31 00:43
Does sideloady not strip the widget and spotlight?

**Comment by Alarez777** [comment] 2024-01-31 01:28
> Does sideloady not strip the widget and spotlight?

I don't know much about it, could you tell me with what program you recommend to load the .ipa? to try it and see if I have the same result.

**Comment by gh0sti** [comment] 2024-01-31 01:38
> > Does sideloady not strip the widget and spotlight?
> 
> 
> 
> I don't know much about it, could you tell me with what program you recommend to load the .ipa? to try it and see if I have the same result.

I use SideStore which asks to install spotlight with an app ID. I click cancel and the app installs.

**Comment by gh0sti** [comment] 2024-01-31 01:39
https://github.com/SideStore/SideStore

**Comment by Alarez777** [comment] 2024-01-31 03:47
> https://github.com/SideStore/SideStore

I used SideStore to install the .ipa from the iphone but the same thing keeps happening when I switch to podcast it closes and cannot be reopened until I uninstall the app.

**Comment by rasmuslos** [comment] 2024-01-31 09:13
I don't think this is related to the program you use to side load. If the app manages to launch (it does, you can see the podcast ui for a very short time) it is something in the app that is causing the crash. Can you side load using Xcode to provide error logs?

**Comment by Alarez777** [comment] 2024-02-08 05:38
> I don't think this is related to the program you use to side load. If the app manages to launch (it does, you can see the podcast ui for a very short time) it is something in the app that is causing the crash. Can you side load using Xcode to provide error logs?

I don't know how to install it with xcode the other day I tried and I had some errors and it didn't let me.
Can't you publish it in beta on Testflight? I understand that when an app crashes it lets you send the logs to the developer.

**Comment by gh0sti** [comment] 2024-02-08 14:39
> > I don't think this is related to the program you use to side load. If the app manages to launch (it does, you can see the podcast ui for a very short time) it is something in the app that is causing the crash. Can you side load using Xcode to provide error logs?
> 
> I don't know how to install it with xcode the other day I tried and I had some errors and it didn't let me. Can't you publish it in beta on Testflight? I understand that when an app crashes it lets you send the logs to the developer.

He has to first get his app on app store which he has been having issues with Apple getting it approved.

**Comment by rasmuslos** [comment] 2024-02-08 14:58
I did talk to someone from the review team about this, apparently there is something wrong with either my account or both my apps, I opened a support ticket and will probably get a call on Friday. But until this is resolved I cannot create a public TestFlight

**Comment by rasmuslos** [comment] 2024-03-13 19:56
> > I don't think this is related to the program you use to side load. If the app manages to launch (it does, you can see the podcast ui for a very short time) it is something in the app that is causing the crash. Can you side load using Xcode to provide error logs?
> 
> I don't know how to install it with xcode the other day I tried and I had some errors and it didn't let me. Can't you publish it in beta on Testflight? I understand that when an app crashes it lets you send the logs to the developer.

Can you give me your E-Mail address? Then I can add you to the TestFlight.

**Comment by gh0sti** [comment] 2024-03-13 20:49
Any chance I can get into the TestFlight?

**Comment by rasmuslos** [comment] 2024-03-14 05:52
> Any chance I can get into the TestFlight?

The TestFlight is on an older version of the app and was only created for this bug report. There is currently no beta on TestFlight, and I sadly don't have a lot of time to work on new features right now.
But when I do create a TestFlight I will keep you posted!

**Comment by Alarez777** [comment] 2024-03-14 05:55
> > > I don't think this is related to the program you use to side load. If the app manages to launch (it does, you can see the podcast ui for a very short time) it is something in the app that is causing the crash. Can you side load using Xcode to provide error logs?
> > 
> > 
> > I don't know how to install it with xcode the other day I tried and I had some errors and it didn't let me. Can't you publish it in beta on Testflight? I understand that when an app crashes it lets you send the logs to the developer.
> 
> Can you give me your E-Mail address? Then I can add you to the TestFlight.

My email is: gerardoalmeyda@icloud.com

**Comment by rasmuslos** [comment] 2024-03-14 14:30
> > > > I don't think this is related to the program you use to side load. If the app manages to launch (it does, you can see the podcast ui for a very short time) it is something in the app that is causing the crash. Can you side load using Xcode to provide error logs?
> > > 
> > > 
> > > I don't know how to install it with xcode the other day I tried and I had some errors and it didn't let me. Can't you publish it in beta on Testflight? I understand that when an app crashes it lets you send the logs to the developer.
> > 
> > 
> > Can you give me your E-Mail address? Then I can add you to the TestFlight.
> 
> My email is: [gerardoalmeyda@icloud.com](mailto:gerardoalmeyda@icloud.com)

Did you receive the E-Mail and can you reproduce the crash?

**Comment by rasmuslos** [comment] 2024-03-15 18:29
Fixed in #63

**Closed by rasmuslos** 2024-03-15 18:29 UTC

**Comment by Alarez777** [comment] 2024-03-17 00:04
> > > > > I don't think this is related to the program you use to side load. If the app manages to launch (it does, you can see the podcast ui for a very short time) it is something in the app that is causing the crash. Can you side load using Xcode to provide error logs?
> > > > 
> > > > 
> > > > I don't know how to install it with xcode the other day I tried and I had some errors and it didn't let me. Can't you publish it in beta on Testflight? I understand that when an app crashes it lets you send the logs to the developer.
> > > 
> > > 
> > > Can you give me your E-Mail address? Then I can add you to the TestFlight.
> > 
> > 
> > My email is: [gerardoalmeyda@icloud.com](mailto:gerardoalmeyda@icloud.com)
> 
> Did you receive the E-Mail and can you reproduce the crash?

No, it doesn't happen anymore, apparently it has been solved.

**Comment by rasmuslos** [comment] 2024-03-17 08:32
This was apparently caused by missing metadata, so if you have your matched your podcast metadata to iTunes it might have resolved it for you.
