### ISSUE TITLE
Stability issues

### ISSUE THREAD

**Issue by saalaataa** [rasmuslos/ShelfPlayer#124] opened 2024-08-08 10:19 UTC
Hi, 
I like the app it may be good alternative to Prologue. 

I am not sure if it is me, but occasionally when I listen to a podcast and switch between applications, and want to switch back to player, application freezes. Especially happens when playback finishes as I want to select and play another episode. Is there a way to examine or send the logs. 

I cleared the cache. My version is 297

**Comment by gugani** [comment] 2024-08-13 17:28
I can confirm the crashes in the application, in my case I have detected that they occur when the application has been in the background and without playing any podcast for a certain time. Never in the middle of a listening session. App version 2.4.2 (297) IOS version: 17.5.1

**Comment by rasmuslos** [comment] 2024-08-14 11:37
Interesting... I am currently in the process of going through the entire codebase to make improvements and it's entirely possible that this bug will be fixed in the next version, so I would like to wait until the next release to further investigate this.

**Comment by rasmuslos** [comment] 2024-09-29 08:37
I found and fixed some bugs that were caused by concurrency (SwiftData implodes if you pass models between threads and apparently arrays are not thread safe in Swift, too). This eliminated most crashes while testing.

**Comment by rasmuslos** [comment] 2024-12-04 16:33
Has the stability improved?

**Closed** 2024-12-09 08:20 UTC
