### ISSUE TITLE
App crashes if podcast details are incomplete

### ISSUE THREAD

**Issue by realchicory** [rasmuslos/ShelfPlayer#63] opened 2024-03-15 01:44 UTC
The app crashes if I try to open a podcast with incomplete details. I verified this by using the "Match" tab on the AudioBookShelf web app to populate the data from iTunes. After all the details are complete, the podcast will open in the app.

**Comment by rasmuslos** [comment] 2024-03-15 06:04
I think another user already reported this, but did not provide a reason. I will look into it

**Comment by rasmuslos** [comment] 2024-03-15 07:41
Can you give me your E-Mail address so that I can add you to a TestFlight so that you can provide a crash report? I am unable to reproduce this

**Comment by realchicory** [comment] 2024-03-15 11:57
I can do that. is there a way to send a private message?

**Comment by rasmuslos** [comment] 2024-03-15 13:28
> I can do that. is there a way to send a private message?

I think I found the issue, but just to be sure, can you send me an E-Mail to git@rfk.io? I will add the address you send the mail from to the TestFlight.

**Comment by realchicory** [comment] 2024-03-15 16:53
OK I sent you an email - I'll test with another incompletely detailed podcast once I have the testflight version

**Comment by realchicory** [comment] 2024-03-15 18:25
I have the testflight version now and it seems like you have fixed the issue as long as there are no episodes downloaded. Once I downloaded an episode of the "incompletely detailed" podcast it starts crashing again when I try to open the podcast in ShelfPlayer.

**Comment by rasmuslos** [comment] 2024-03-15 18:28
> I have the testflight version now and it seems like you have fixed the issue as long as there are no episodes downloaded. Once I downloaded an episode of the "incompletely detailed" podcast it starts crashing again when I try to open the podcast in ShelfPlayer.

The TestFlight in running on an older version of ShelfPlayer, but the issue was related to the parsing of episodes from the ABS server. It actually was the bug I fixed in https://github.com/rasmuslos/ShelfPlayer/commit/cb94938932084115ee039d5afe3ac019dd4d0510 . All that is left now is to publish a new version on the AppStore, it should arrive in the next few days.

I would recommend going back to the AppStore version, because this TestFlight group is not on the latest release.
Thank you for your help!

**Closed by rasmuslos** 2024-03-15 18:28 UTC
