### ISSUE TITLE
Cannot connect through URL address

### ISSUE THREAD

**Issue by Hafumoto** [rasmuslos/ShelfPlayer#68] opened 2024-03-20 20:25 UTC
For some reason, when trying to connect through a URL address, I'm met with a "Audiobookshelf server not found" message. It doesn't even seem to try to connect. If I use the local IP connected through the local network, I get right in.

Example:
I try connecting through http://myown.url.com:1234. I get "Audiobookshelf server not found". If I try the same in a browser, I get right in.
If I try http://192.168.1.100:11378, I get straight in.

I do know that my URL works, as I've been using it with the official Audiobookshelf app.

**Comment by gh0sti** [comment] 2024-03-20 20:55
I think you need to have https so you'll need to setup a reverse proxy.

**Comment by rasmuslos** [comment] 2024-03-20 21:22
Ig you are not on the latest version this could be the cause, update the app if you are not.

What ip address is your domain resolving to? Is it you local one or is the traffic routed through the public internet?

**Comment by Hafumoto** [comment] 2024-03-21 18:34
I'm on 2.3.1. I usually connect through a DDNS set up by my Asus router. Again, it works in other apps and in the browser.

**Comment by rasmuslos** [comment] 2024-03-21 21:44
You are technically on the latest side loaded version, but `2.3.3` is already in the AppStore with a bug fix for this. I will release a new version for side loading when the new now playing animation is finished.

This version should work:
[ShelfPlayer.ipa.zip](https://github.com/rasmuslos/ShelfPlayer/files/14711483/ShelfPlayer.ipa.zip)

**Closed by rasmuslos** 2024-03-21 21:44 UTC
