### ISSUE TITLE
[Feature Request] Ability to view accompanying PDF

### ISSUE THREAD

**Issue by sachinjaincs** [rasmuslos/ShelfPlayer#112] opened 2024-06-09 10:11 UTC
Hello,
I greatly appreciate and enjoy the aesthetics of the application. Many of the Audiobook have PDFs accompanying them. It would be great to if these PDFs are available to open inside the Audiobook page above chapter.

Here an example:

![RPReplay_Final1717927606-ezgif com-video-to-gif-converter](https://github.com/rasmuslos/ShelfPlayer/assets/48393913/530c373a-a3e3-49f4-8e2f-de4b3e828b3f)

Thank you 😊

**Comment by rasmuslos** [comment] 2024-06-14 12:02
Duplicate of https://github.com/rasmuslos/ShelfPlayer/issues/35

The implementation would have to be the same for both

**Closed** 2024-06-14 12:02 UTC
